name: E2E Tests

on:
  pull_request:
    branches:
      - main
  # This workflow can also be triggered manually with a deployment URL
  workflow_dispatch:
    inputs:
      deployment_url:
        description: 'Netlify deployment URL to test'
        required: true

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Wait for Netlify deployment
        uses: jakepartusch/wait-for-netlify-action@v1.4
        id: wait-for-netlify
        if: github.event_name == 'pull_request'
        with:
          site_name: 'bluesky-pwa'
          max_timeout: 300

      - name: Run Playwright tests against Netlify deployment
        if: github.event_name == 'pull_request'
        run: npm run test:e2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.wait-for-netlify.outputs.url }}

      - name: Run Playwright tests against custom URL
        if: github.event_name == 'workflow_dispatch'
        run: npm run test:e2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.inputs.deployment_url }}

      - name: Upload test results
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
